/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    packages: Package;
    destinations: Destination;
    cruises: Cruise;
    testimonials: Testimonial;
    leads: Lead;
    media: Media;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    destinations: {
      packages: 'packages';
    };
  };
  collectionsSelect: {
    packages: PackagesSelect<false> | PackagesSelect<true>;
    destinations: DestinationsSelect<false> | DestinationsSelect<true>;
    cruises: CruisesSelect<false> | CruisesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * The Packages we sell. Each has a starting price, what’s included, and photos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: number;
  /**
   * The name travellers see, e.g. “Maldives Escape”.
   */
  title: string;
  /**
   * Auto-generated from the title if left blank. Used in the page URL.
   */
  slug: string;
  /**
   * The country this Package sells to, e.g. Maldives.
   */
  country: string;
  /**
   * How long the trip is, e.g. “5 Days 4 Nights”.
   */
  duration: string;
  /**
   * The “from” price. Shown as “Starting $X” - never a checkout total.
   */
  startingPrice: number;
  /**
   * The Destination this Package is grouped under.
   */
  destination?: (number | null) | Destination;
  /**
   * A short, inviting blurb about the Package.
   */
  information: string;
  /**
   * What the Starting Price covers - add one line per item.
   */
  inclusions?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The main image shown on Package cards and the detail hero.
   */
  heroImage?: (number | null) | Media;
  /**
   * Extra photos shown on the Package detail page.
   */
  gallery?: (number | Media)[] | null;
  /**
   * Show in the home-page “Popular Tours” highlights.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Destinations we send travellers to. Group Packages under one and give it a photo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations".
 */
export interface Destination {
  id: number;
  /**
   * The Destination name, e.g. Turkey or Maldives.
   */
  name: string;
  /**
   * Auto-generated from the title if left blank. Used in the page URL.
   */
  slug: string;
  /**
   * The main image shown on Destination cards and the Destination page.
   */
  heroImage?: (number | null) | Media;
  /**
   * Show in the home-page “Top Destinations” highlights.
   */
  featured?: boolean | null;
  /**
   * Packages that sell to this Destination.
   */
  packages?: {
    docs?: (number | Package)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Your shared photo library. Every image needs a short description for accessibility.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describes the image for screen readers and when it fails to load.
   */
  alt: string;
  /**
   * Original import URL. Set by the seed routine and used to avoid re-importing the same image.
   */
  sourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Cruise holidays, browsed on their own page separately from land Packages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cruises".
 */
export interface Cruise {
  id: number;
  /**
   * The name travellers see, e.g. “Greek Isles Cruise”.
   */
  title: string;
  /**
   * Auto-generated from the title if left blank. Used in the page URL.
   */
  slug: string;
  /**
   * The country or region this Cruise sails, e.g. Italy.
   */
  country: string;
  /**
   * How long the cruise is, e.g. “8 Days 7 Nights”.
   */
  duration: string;
  /**
   * The “from” price. Shown as “Starting $X” - never a checkout total.
   */
  startingPrice: number;
  /**
   * A short, inviting blurb about the Cruise itinerary.
   */
  information: string;
  /**
   * The main image shown on Cruise cards and the detail hero.
   */
  heroImage?: (number | null) | Media;
  /**
   * Extra photos shown on the Cruise detail page.
   */
  gallery?: (number | Media)[] | null;
  /**
   * Show in the home-page highlights.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Traveller quotes shown as social proof. Tick “Featured” to show one on the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * The traveller’s words, in their voice.
   */
  quote: string;
  /**
   * Who gave this quote.
   */
  authorName: string;
  /**
   * Their home town or country, e.g. Beirut.
   */
  authorLocation?: string | null;
  /**
   * The trip they took, e.g. Maldives.
   */
  trip?: string | null;
  /**
   * Star rating out of 5.
   */
  rating?: number | null;
  /**
   * Optional photo of the traveller.
   */
  avatar?: (number | null) | Media;
  /**
   * Show in the home-page testimonials.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Enquiries sent in from the website. Follow up by phone or WhatsApp - nothing here is a paid booking.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  /**
   * Who sent the enquiry.
   */
  name: string;
  /**
   * How to reach them - phone, email, or WhatsApp.
   */
  contact: string;
  /**
   * When they hope to travel (free text).
   */
  preferredDates?: string | null;
  /**
   * How many people are travelling.
   */
  partySize?: number | null;
  /**
   * What they wrote in the enquiry form.
   */
  message?: string | null;
  /**
   * The kind of trip enquired about.
   */
  tripType?: ('package' | 'cruise') | null;
  /**
   * The Package/Cruise title at the time of enquiry.
   */
  tripTitle?: string | null;
  tripSlug?: string | null;
  /**
   * The Starting Price shown when they enquired.
   */
  tripStartingPrice?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Staff who can sign in to this admin panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'packages';
        value: number | Package;
      } | null)
    | ({
        relationTo: 'destinations';
        value: number | Destination;
      } | null)
    | ({
        relationTo: 'cruises';
        value: number | Cruise;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  country?: T;
  duration?: T;
  startingPrice?: T;
  destination?: T;
  information?: T;
  inclusions?:
    | T
    | {
        item?: T;
        id?: T;
      };
  heroImage?: T;
  gallery?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations_select".
 */
export interface DestinationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  heroImage?: T;
  featured?: T;
  packages?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cruises_select".
 */
export interface CruisesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  country?: T;
  duration?: T;
  startingPrice?: T;
  information?: T;
  heroImage?: T;
  gallery?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  authorName?: T;
  authorLocation?: T;
  trip?: T;
  rating?: T;
  avatar?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  contact?: T;
  preferredDates?: T;
  partySize?: T;
  message?: T;
  tripType?: T;
  tripTitle?: T;
  tripSlug?: T;
  tripStartingPrice?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Contact details, socials, home-page numbers, and the site assistant - all in one place.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Mobile "Call us" numbers, shown in the header/footer.
   */
  mobiles?:
    | {
        number: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Land-line phone number.
   */
  landline?: string | null;
  /**
   * Public "Write to us" email address.
   */
  email?: string | null;
  /**
   * Physical address.
   */
  address?: string | null;
  /**
   * WhatsApp number in international format, digits only (e.g. 96181800480). Used to build wa.me deep links.
   */
  whatsapp?: string | null;
  /**
   * Social profile links.
   */
  socials?: {
    instagram?: string | null;
    facebook?: string | null;
  };
  /**
   * The trust figures shown on the home page (animated counters).
   */
  proofMetrics?: {
    yearsExperience?: number | null;
    destinationsCount?: number | null;
    flightBookings?: number | null;
    amazingTours?: number | null;
    happyClients?: number | null;
    cruisesBookings?: number | null;
  };
  /**
   * Short brand line shown in the footer.
   */
  footerTagline?: string | null;
  /**
   * The floating assistant shown in the corner of the site.
   */
  assistant?: {
    /**
     * Uncheck to hide the assistant everywhere on the site.
     */
    enabled?: boolean | null;
    /**
     * Opening message shown when the panel is opened. Falls back to a default when blank.
     */
    greeting?: string | null;
    /**
     * Chips shown in the panel. Leave empty to show just the greeting.
     */
    actions?:
      | {
          /**
           * Chip text, e.g. “Explore Cruises”.
           */
          label: string;
          /**
           * Optional leading emoji, e.g. 🚢.
           */
          emoji?: string | null;
          /**
           * What the chip does when tapped.
           */
          type: 'route' | 'faq' | 'whatsapp' | 'enquiry';
          /**
           * Internal path to open, e.g. /cruises (or /contact for an enquiry).
           */
          target?: string | null;
          /**
           * Answer shown inline when the chip is tapped. Blank lines start a new paragraph.
           */
          answer?: string | null;
          /**
           * Optional message prefilled in WhatsApp. Uses the site WhatsApp number; the chip is hidden if none is set.
           */
          message?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  mobiles?:
    | T
    | {
        number?: T;
        id?: T;
      };
  landline?: T;
  email?: T;
  address?: T;
  whatsapp?: T;
  socials?:
    | T
    | {
        instagram?: T;
        facebook?: T;
      };
  proofMetrics?:
    | T
    | {
        yearsExperience?: T;
        destinationsCount?: T;
        flightBookings?: T;
        amazingTours?: T;
        happyClients?: T;
        cruisesBookings?: T;
      };
  footerTagline?: T;
  assistant?:
    | T
    | {
        enabled?: T;
        greeting?: T;
        actions?:
          | T
          | {
              label?: T;
              emoji?: T;
              type?: T;
              target?: T;
              answer?: T;
              message?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}